[project]
name = "formant-annotation-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "fasttrackpy>=0.6.1",
    "jinja2>=3.1.6",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.49",
]
