[project]
name = "formant-annotation-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "fasttrackpy",
    "jinja2>=3.1.6",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.49",
    # Needed for Intel macOS compatibility
    "numba<0.62.1",
    "llvmlite<0.47",
    "formants-export",
]

[tool.uv.sources]
fasttrackpy = { git = "https://github.com/massimolipari/fasttrackpy.git", rev = "e776cd2af01835fc935a8316b0d5c231961efdae" }
formants-export = { git = "ssh://git@github.com/massimolipari/formants.git", rev = "exporting" }
